site_name: My IBM Cloud Private resources (last updated on 18 Mar 2019)
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Solution: solution.md
    - Learning: learning.md
    - Best Practices: ./security/bestpractices.md
    - Security: ./security/security.md
    - How-To Guides: howto.md
    - Troubleshoot Kubernetes Deployments: troubleshoot.md
    - Contact: contact.md
    - About: about.md
#theme: readthedocs
theme:
  name: 'material'